micronaut:
  application:
    name: awesomeBlogServer
  security:
    authentication: idtoken
    oauth2:
      clients:
        cognito:
          client-id: '${OAUTH_CLIENT_ID:xxx}'
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}'
          openid:
            issuer: 'https://cognito-idp.${AWS_REGION:ap-northeast-1}.amazonaws.com/${COGNITO_POOL_ID:12345}/'
    endpoints:
      logout:
        get-allowed: true
    token:
      jwt:
        signatures:
          jwks:
            cognito:
              url: 'https://cognito-idp.${AWS_REGION:ap-northeast-1}.amazonaws.com/${AWS_REGION:ap-northeast-1}-${COGNITO_POOL_ID:12345}/.well-known/jwks.json'

dynamodb:
  object-table-name: 'awesome-blog-dev-object-table'
  relation-table-name: 'awesome-blog-dev-relation-table'
  local:
    host: localhost
    port: 8000
