name: Build
on:
  workflow_call:
    inputs:
      dry-run:
        description: to prevent upload artifacts, set '1'
        required: false
        type: boolean
        default: false
      build-version:
        description: build date
        required: false
        type: string
        default: noversion
      java-version:
        description: builder container name
        required: false
        type: string
        default: 17
      graalvm-version:
        description: builder container name
        required: false
        type: string
        default: 22
    outputs:
      artifact-name:
        description: Name of artifact to upload
        value: awesome-blog-backend
      build-version:
        description: build date
        value: ${{ inputs.build-version }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/graalvm/graalvm-ce:ol9-java${{ inputs.java-version }}-${{ inputs.graalvm-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: .m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Maven Package
        run: |
          chmod +x ./mvnw
          ./mvnw package -Dpackaging=native-image -Dmicronaut.runtime=lambda -Pgraalvm

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: awesome-blog-backend-java${{ inputs.java-version }}-${{ inputs.graalvm-version }}
          path: ./target/awesome-blog-server*
          retention-days: 1

  upload:
    if: inputs.dry-run != true
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: awesome-blog-backend-java${{ inputs.java-version }}-${{ inputs.graalvm-version }}
          path: ./awesome-blog-backend

      - name: Rename Artifact
        run: mv ./awesome-blog-backend/awesome-blog-server bootstrap

      - name: Zip lambda
        run: zip -rj function.zip bootstrap

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          aws-region: ap-northeast-1

      - id: Upload
        name: Upload
        run: |
          echo ${{ inputs.build-version}}
          aws s3 cp \
          function.zip \
          s3://awesome-blog-an1-dev-mdl/artifact/blog/backend/${{ inputs.build-version}}/java${{ inputs.java-version }}-${{ inputs.graalvm-version }}/
