name: Test
on:
  workflow_call:

jobs:
  lint-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        uses: reviewdog/action-actionlint@v1

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/graalvm/graalvm-ce:ol8-java17-22
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: .m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Maven Test
        run: |
          chmod +x ./mvnw
          ./mvnw install test
        env:
          AWS_REGION: ap-northeast-1
