name: Build on push main
on:
  push:
    branches:
      - main

jobs:
  codeQL:
    uses: ./.github/workflows/_codeql.yaml

  test:
    uses: ./.github/workflows/_test.yaml

  build-version:
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.BuildVersion.outputs.build-version }}
    steps:
      - id: BuildVersion
        name: BuildVersion
        run: echo "build-version=v$(date +"%Y%m%d%H%M")" >> "$GITHUB_OUTPUT"

  build:
    needs:
      - test
      - build-version
    strategy:
      matrix:
        packaging: [ native-image, jar ]
        java-version: [ 11, 17 ]
        graalvm-version: [ 22 ]
    uses: ./.github/workflows/_build.yaml
    with:
      build-version: ${{ needs.build-version.outputs.build-version }}
      packaging: ${{ matrix.packaging }}
      java-version: ${{ matrix.java-version }}
      graalvm-version: ${{ matrix.graalvm-version }}
      stable: java17-22-native-image
    secrets: inherit

  tag:
    needs:
      - build
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.Tag.outputs.build-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OWNER_PAT }}

      - id: Tag
        name: Push Tag
        run: |
          echo ${{ needs.build.outputs.build-version}}
          git tag ${{ needs.build.outputs.build-version}}
          git push origin ${{ needs.build.outputs.build-version}}
          echo "build-version=${{ needs.build.outputs.build-version}}" >> "$GITHUB_OUTPUT"
