name: Check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
      - '!main'

jobs:
  dependency-review:
    uses: ./.github/workflows/_dependency-review.yaml

  codeQL:
    uses: ./.github/workflows/_codeql.yaml
    
  test:
    uses: ./.github/workflows/_test.yaml
