name: Check on receive pull request
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
      - '!main'

jobs:
  codeQL:
    uses: ./.github/workflows/_codeql.yaml

  test:
    uses: ./.github/workflows/_test.yaml
