name: Build on push main
on:
  push:
    branches:
      - main

jobs:
  codeQL:
    uses: ./.github/workflows/_codeql.yaml

  test:
    uses: ./.github/workflows/_test.yaml

  build:
    needs:
      - test
    uses: ./.github/workflows/_build.yaml

  deploy-dev:
    needs:
      - build
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: awesome-blog-client

      - name: Create function.zip
        run: |
          mv awesome-blog-server bootstrap
          zip function.zip boostrap

      - name: CloudFormation
        run: echo TODO cfn
